import * as stylex from "@stylexjs/stylex";
import {
    colors,
    spacing,
    radius,
    text,
} from "../../../app/globalTokens.stylex";

export const baseStyles = stylex.create({
    wrapper: {
        display: "inline-block",
        position: "relative",
    },
    button: {
        alignItems: "center",
        backgroundColor: {
            default: `rgba(${colors.bgTertiaryR}, ${colors.bgTertiaryG}, ${colors.bgTertiaryB}, 1)`,
            ":hover": `rgba(${colors.bgTertiaryHoverR}, ${colors.bgTertiaryHoverG}, ${colors.bgTertiaryHoverB}, 1)`,
        },
        borderRadius: "50%",
        borderWidth: 0,
        cursor: "pointer",
        display: "flex",
        justifyContent: "center",
        minHeight: 40,
        minWidth: 40,
        position: "relative",
    },
    arrow: {
        alignItems: "center",
        backgroundColor: `rgba(${colors.bgTertiaryR}, ${colors.bgTertiaryG}, ${colors.bgTertiaryB}, 1)`,
        borderColor: `rgba(${colors.bgSecondaryR}, ${colors.bgSecondaryG}, ${colors.bgSecondaryB}, 1)`,
        borderRadius: "50%",
        borderStyle: "solid",
        borderWidth: 2,
        bottom: -3,
        display: "flex",
        height: 14,
        justifyContent: "center",
        position: "absolute",
        right: 0,
        width: 14,
    },
    dropdown: {
        backgroundColor: `rgba(${colors.bgSecondaryR}, ${colors.bgSecondaryG}, ${colors.bgSecondaryB}, 1)`,
        borderRadius: radius.md,
        boxShadow: `0 1px 2px rgba(${colors.shadowR}, ${colors.shadowG}, ${colors.shadowB}, .2)`,
        marginTop: spacing.xs,
        minWidth: 360,
        padding: `${spacing.xs} ${spacing.xxs}`,
        position: "absolute",
        right: 0,
    },
    item: {
        backgroundColor: {
            default: "transparent",
            ":hover": `rgba(${colors.bgTertiaryR}, ${colors.bgTertiaryG}, ${colors.bgTertiaryB}, 1)`,
        },
        borderRadius: radius.sm,
        caretColor: "transparent",
        cursor: "pointer",
        marginBottom: spacing.xxxs,
        marginLeft: spacing.lg,
        padding: `${spacing.xxs}`,
    },
    itemContent: {
        alignItems: "center",
        display: "flex",
        justifyContent: "space-between",
    },
    itemTitle: {
        display: "block",
        fontWeight: 600,
    },
    itemDescription: {
        color: `rgba(${colors.textSecondaryR}, ${colors.textSecondaryG}, ${colors.textSecondaryB}, 1)`,
        display: "block",
        fontSize: text.xs,
        paddingRight: spacing.sm,
    },
    radio: {
        backgroundColor: "transparent",
        borderRadius: "50%",
        flexShrink: 0,
        height: 12,
        left: "-4px",
        outlineColor: `rgba(${colors.borderR}, ${colors.borderG}, ${colors.borderB}, 1)`,
        outlineOffset: "2px",
        outlineStyle: "solid",
        outlineWidth: "2px",
        position: "relative",
        width: 12,
    },
    radioSelected: {
        backgroundColor: `rgba(${colors.primaryR}, ${colors.primaryG}, ${colors.primaryB}, 1)`,
        borderColor: `rgba(${colors.primaryR}, ${colors.primaryG}, ${colors.primaryB}, 1)`,
        outlineColor: `rgba(${colors.primaryR}, ${colors.primaryG}, ${colors.primaryB}, 1)`,
    },
});
